# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "e-Novel"
license = "MIT"
licenselink = "https://github.com/Ashenara/e-Novel/blob/main/LICENSE"
description = "Showcase, Reading, and responsive Hugo theme"
homepage = "https://ashenara.com"
demosite = "https://arashe.com"
tags = [
  "responsive",
  "simple",
  "clean",
  "light",
  "dark",
  "blog",
  "search"
]
features = [
  "responsive",
  "e-book",
  "e-reading",
  "e-novel",
  "blog",
  "cover-image",
  "table-of-contents",
  "favicon",
  "cover",
  "social-icons",
  "minified-assets",
  "theme-toggle",
  "search"
]
min_version = "0.147.7"

[author]
  name = "Ashenara"
  homepage = "https://github.com/ashenara/"